title: Ian Ho # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of experience in Data Analysis and Data Science. Extensive work on customer profiling, segmentation, content consumption and purchasing behaviour. 
  Additionally, involved in the development, maintenance, and operation of forecast models related to customer churn and viewership behaviour. 
  <br><br>
  Currently with Astro Malaysia serving the the Data team as a Data Scientist. 
  Possess a Master's Degree in Electrical and Electronic Engineering from the University of Bath, UK (2019) and a Research Master's Degree in Engineering Science from Multimedia University, Malaysia (2023) in the field of Natural Language Processing.
  <br><br>
  <a href="https://www.linkedin.com/in/ianhohj/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
