title: Ian Ho # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Currently with Astro Malaysia as a Data Scientist. AWS Certified Solution Architect (soon...)
  Achieved a Master's Degree in Electrical and Electronic Engineering from the University of Bath, UK (2019) 
  and a Research Master's Degree in Engineering Science from Multimedia University, Malaysia (2023) in the field of Natural Language Processing.
  <br><br>
  <a href="https://www.linkedin.com/in/ianhohj/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
